SELECT USER
FROM DUAL;
-- HR


-- ▼ 세 개 이상의 테이블 조인(JOIN)

-- ① SQL 1992 CODE
/*
SELECT 테이블명1.컬럼명, 테이블명2.컬럼명, 테이블명3.컬럼명
FROM 테이블명1, 테이블명2, 테이블명3
WHERE 테이블명1.컬럼명1 = 테이블명2.컬럼명1
  AND 테이블명2.컬럼명2 = 테이블명3.컬럼명2;
*/

-- ② SQL 1999 CODE
/*
SELECT 테이블명1.컬럼명, 테이블명2.컬럼명, 테이블명3.컬럼명
FROM 테이블명1 JOIN 테이블명2
ON 테이블명1.컬럼명1 = 테이블명2.컬럼명1
        JOIN 테이블명3
        ON 테이블명2.컬럼명2 = 테이블명3.컬럼명2;
*/


-- HR계정 소유의 테이블 또는 뷰 목록 조회
SELECT *
FROM TAB;
/*
COUNTRIES	        TABLE	
DEPARTMENTS	        TABLE	
EMPLOYEES	        TABLE	
EMP_DETAILS_VIEW	VIEW	
JOBS	            TABLE	
JOB_HISTORY	        TABLE	
LOCATIONS	        TABLE	
REGIONS	            TABLE	
*/


-- ▼ HR.JOBS, HR.EMPLOYEES, HR.DEPARTMENTS 테이블을 대상으로 직원들의 데이터를
--    FIRST_NAME, LAST_NAME, JOB_TITLE, DEPARTMENT_NAME 항목으로 조회한다.
--           EMPLOYEES          JOBS      DEPARTMENTS

/* 선생님 해설

SELECT *
FROM DEPARTMENTS;
-- DEPARTMENTS_ID (관계컬럼)
SELECT *
FROM DEPARTMENTS;
-- JOB_ID         (관계컬럼)
SELECT *
FROM DEPARTMENTS;

*/

SELECT E.FIRST_NAME, E.LAST_NAME, J.JOB_TITLE, D.DEPARTMENT_NAME
FROM HR.JOBS J RIGHT JOIN HR.EMPLOYEES E
ON J.JOB_ID = E.JOB_ID
        LEFT JOIN HR.DEPARTMENTS D
        ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;


-- ▼ EMPLOYEES, DEPARTMENTS, JOBS, LOCATIONS, COUNTRIES, REGIONS 테이블을 대상으로
--    직원들의 데이터를 다음과 같이 조회한다.
--    FIRST_NAME, LAST_NAME, JOB_TITLE, DEPARTMENT_NAME, CITY,  COUNTRY_NAME, REGION_NAME
--          EMPLOYEES           JOBS      DEPARTMENTS  LOCATIONS  COUNTRIES     REGIONS

DESC JOBS;
-- JOB_ID
DESC EMPLOYEES;
-- DEPARTMENT_ID
DESC DEPARTMENTS;
-- LOCATION_ID
DESC LOCATIONS;
-- COUNTRY_ID
DESC COUNTRIES;
-- REGION_ID
DESC REGIONS;

SELECT E.FIRST_NAME, E.LAST_NAME, J.JOB_TITLE, D.DEPARTMENT_NAME, L.CITY, C.COUNTRY_NAME, R.REGION_NAME
FROM JOBS J JOIN EMPLOYEES E
ON J.JOB_ID = E.JOB_ID
        LEFT JOIN DEPARTMENTS D
        ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
                LEFT JOIN LOCATIONS L
                ON D.LOCATION_ID = L.LOCATION_ID
                        LEFT JOIN COUNTRIES C
                        ON L.COUNTRY_ID = C.COUNTRY_ID
                                LEFT JOIN REGIONS R
                                ON C.REGION_ID = R.REGION_ID;
























